WebClient/Models/ErrorViewModel.cs
using System;

namespace WebClient.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebClient/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebClient.Controllers
{
    public class AuthorsController : Controller
    {
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebClient/Controllers/BooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebClient.Controllers
{
    public class BooksController : Controller
    {
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebClient/Controllers/HomeController.cs
using DataLayer.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using WebApi.DTOs;
using WebClient.Models;

namespace WebClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Detail(int? id)
        {

            List<BookDTO> books = new List<BookDTO>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44310/api/");
                var reponseTask = client.GetAsync("Books/" + id);
                reponseTask.Wait();

                var result = reponseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsStringAsync();
                    readTask.Wait();
                    string json_data = JsonConvert.SerializeObject(readTask.Result); 
                    var book = JsonConvert.DeserializeObject(json_data).ToString();
                    var resultBook = JsonConvert.DeserializeObject<BookDTO>(book);
                    books.Add(resultBook);
                }
            }
            ViewBag.Book = books;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

WebClient/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using WebApi.Models.Identities;
using static WebApi.Controllers.IdentityController;

namespace WebClient.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Index(LoginModel loginModel)
        {

            if(!ModelState.IsValid)
            {
                return View(loginModel);
            }

            HttpClient client = new HttpClient();
            StringContent body = new StringContent(JsonConvert.SerializeObject(loginModel), System.Text.Encoding.UTF8, "application/json");
            string url = "https://localhost:44310/api/Identity/RequiredToken";

            var response = client.PostAsync(url, body).Result;
            if(response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                string raw = response.Content.ReadAsStringAsync().Result;
                HttpContext.Session.SetString("authentication", raw);
                return RedirectToAction("Index", "Home");
            }

            var message = response.Content.ReadAsStringAsync().Result;
            ViewData["ApiMessage"] = message;
            return View(loginModel);
        }
    }
}

WebClient/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebClient.Extentions;

namespace WebClient.Controllers
{
    public class LogoutController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            SessionManager.Logout(HttpContext);
            return RedirectToAction("Index", "Home");
        }
    }
}

WebClient/Controllers/PublishersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebClient.Controllers
{
	public class PublishersController : Controller
	{
        [Authorize(Roles = "Admin")]
		public IActionResult Index()
		{
			return View();
		}
	}
}

WebClient/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using WebApi.DTOs;
using WebApi.Models.Users;

namespace WebClient.Controllers
{
    public class UsersController : Controller
    {

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Register()
        {
            return View();
        }
        
    }
}

WebClient/Views/Authors/Index.cshtml
@{
	ViewData["Title"] = "Authors";
}

<div class="card">
	<div class="card-header">Authors Panel</div>
	<div class="card-body">
		<div class="row">
			<div class="col-md-12 text-white text-center">
				<button id="btn-refresh" class="btn btn-primary">Refresh</button>
				<button id="btn-create" class="btn btn-secondary">Create New</button>
			</div>
			<div class="col-md-12">
				<form id="form_create" autocomplete="off">
					<h4>Please fill information below</h4>
					<hr />
					<div class="row">
						<div class="form-group col-lg-4 col-md-6">
							<label for="FirstName_Create">FirstName</label>
							<input type="text" class="form-control" id="FirstName_Create" name="FirstName" placeholder="Enter FirstName"/>
						</div>
						<div class="form-group col-lg-4 col-md-6">
							<label for="LastName_Create">FirstName</label>
							<input type="text" class="form-control" id="LastName_Create" name="LastName" placeholder="Enter LastName"/>
						</div>

						<div class="form-group col-lg-4 col-md-6">
							<label for="Phone_Create">Phone</label>
							<input type="text" class="form-control" id="Phone_Create" name="Phone" placeholder="Enter Phone"/>
						</div>

						<div class="form-group col-lg-4 col-md-6">
							<label for="Email_Create">Email</label>
							<input type="email" class="form-control" id="Email_Create" name="Email" placeholder="Enter Email"/>
						</div>

						<div class="form-group col-lg-4 col-md-6">
							<label for="Address_Create">Address</label>
							<input type="text" class="form-control" id="Address_Create" name="Address" placeholder="Enter Address"/>
						</div>
					
						<div class="form-group col-lg-4 col-md-6">
							<label for="City_Create">City</label>
							<select class="form-control" id="City_Create" name="City" placeholder="Select City">

							</select>
						</div>
						<div class="form-group col-lg-4 col-md-6">
							<label for="State_Create">State</label>
							<select class="form-control" id="State_Create" name="State" placeholder="Select State">

							</select>
						</div>

						<div class="form-group col-lg-4 col-md-6">
							<label for="ZipCode_Create">ZipCode</label>
							<input type="text" class="form-control" id="ZipCode_Create" name="ZipCode" placeholder="Enter ZipCode"/>
						</div>
						
						<div class="m-2 col-sm-12 text-center">
							<button type="button" id="form_create_close" class="btn btn-danger">Close</button>
							<button type="submit" class="btn btn-success">Create</button>
						</div>
					</div>
				</form>

			</div>
			<div class="col-md-12">
				<h4>Information</h4>
				<hr />
				<table id="table_items" class="table table-striped table-hover table-md-responsive text-center">
					<thead class="bg-primary text-white">
						<tr>
							<th>Id</th>
							<th>FullName</th>
							<th>Phone</th>
							<th>Email</th>
							<th>Address</th>
							<th>City</th>
							<th>State</th>
							<th>ZipCode</th>
							<th>...</th>
						</tr>
						<tr id="loading">
							<td colspan="8">
								<div class="spinner-border text-secondary" role="status">
									<span class="sr-only">Loading...</span>
								</div>
							</td>
						</tr>
					</thead>
					<tbody>
						
					</tbody>
				</table>
				

				<form id="form_update" autocomplete="off" style="gap: 10px">
					<hr />

					<div class="row">

						<div class="form-group col-lg-4 col-md-6">
							<label for="Id_Update">Id</label>
							<input type="text" readonly class="form-control" id="Id_Update" name="Id"/>
						</div>

						<div class="form-group col-lg-4 col-md-6">
							<label for="FirstName_Update">FirstName</label>
							<input type="text" class="form-control" id="FirstName_Update" name="FirstName" placeholder="Enter FirstName"/>
						</div>

						<div class="form-group col-lg-4 col-md-6">
							<label for="LastName_Update">LastName</label>
							<input type="text" class="form-control" id="LastName_Update" name="LastName" placeholder="Enter LastName"/>
						</div>

						<div class="form-group col-lg-4 col-md-6">
							<label for="Phone_Update">Phone</label>
							<input type="text" class="form-control" id="Phone_Update" name="Phone" placeholder="Enter Phone"/>
						</div>

						<div class="form-group col-lg-4 col-md-6">
							<label for="Email_Update">Email</label>
							<input type="email" class="form-control" id="Email_Update" name="Email" placeholder="Enter Email"/>
						</div>

						<div class="form-group col-lg-4 col-md-6">
							<label for="Address_Update">Address</label>
							<input type="text" class="form-control" id="Address_Update" name="Address" placeholder="Enter Address"/>
						</div>
					
						<div class="form-group col-lg-4 col-md-6">
							<label for="City_Update">City</label>
							<select class="form-control" id="City_Update" name="City" placeholder="Select City">

							</select>
						</div>
						<div class="form-group col-lg-4 col-md-6">
							<label for="State_Update">State</label>
							<select class="form-control" id="State_Update" name="State" placeholder="Select State">

							</select>
						</div>

						<div class="form-group col-lg-4 col-md-6">
							<label for="ZipCode_Update">ZipCode</label>
							<input type="text" class="form-control" id="ZipCode_Update" name="ZipCode" placeholder="Enter ZipCode"/>
						</div>
						
						<div class="m-2 col-sm-12 text-center">
							<button type="button" id="form_update_close" class="btn btn-danger">Close</button>
							<button type="submit" class="btn btn-success">Save</button>
						</div>
					</div>
				</form>

			</div>
		</div>
	</div>

</div>

@section Scripts {

<script>

// Definition

var baseUrl = "https://localhost:44310/api/";
var itemList = [];
var selectedItem = null;
var selectedIndex = -1;

var getAllItems = function() {

	$("#table_items").show();
    $("#loading").show();

	$.get(baseUrl + "Authors", function(data, status)
	{
        if (status == "success") {
			$("#loading").hide(0.5);
            itemList = data;
            console.log(itemList);
            renderItems(itemList);
        }
        else {
            alert(data);
		}
	});

}

var renderItems = function(dataset) {
            
    let dataRow = "";
	
	dataset.forEach((item, idx) => {
        dataRow += 
		`
		<tr id="${item.id}">
			<td>${item.id}</td>
			<td>${item.fullName}</td>
			<td>${item.phone}</td>
			<td>${item.email}</td>
			<td>${item.address}</td>
			<td>${item.city.name}</td>
			<td>${item.state.name}</td>
			<td>${item.zipCode}</td>
			<td>
				<button name="btn-update" class="btn btn-success m-1" value="${idx}">Edit</button>
				<button name="btn-delete" class="btn btn-danger m-1" value="${idx}">Remove</button>
			</td>
		<tr>
		`;
    });

    $("#table_items tbody").html(dataRow);
    addFillDataEvent();

}

var addFillDataEvent = () => {
	$("button[name='btn-update']").click(updateBtnClicked);
	$("button[name='btn-delete']").click(deleteBtnClicked);
}

var updateBtnClicked = (e) => {

    console.log("update clicked!");
    let idx = e.currentTarget.value;
    selectedItem = itemList[idx];
    selectedIndex = idx;

    fillInfo(selectedItem);

	$("#form_update").show(0.8);
    $("#form_create").hide(0.8);
}

var fillInfo = function(item) {
    $("#Id_Update").val(item.id);
    $("#FirstName_Update").val(item.firstName);
    $("#LastName_Update").val(item.lastName);
    $("#Phone_Update").val(item.phone);
    $("#Email_Update").val(item.email);
    $("#Address_Update").val(item.address);
    $("#City_Update").val(item.city.id);
    $("#State_Update").val(item.state.id);
    $("#ZipCode_Update").val(item.zipCode);
};

var deleteBtnClicked = (e) => {
	console.log("delete clicked!");
            
	let idx = e.currentTarget.value;
	let deleteSelectedItem = itemList[idx];
    console.log(idx);
    console.log(deleteSelectedItem);
    if (confirm(`Delete author with Id=${deleteSelectedItem.id}? You cannot reverse data!`)) {
				
		$.ajax({
		type: 'delete',
        headers: {
			"Content-Type": "application/json"
		},
		url: baseUrl + "Authors" + "/" + deleteSelectedItem.id,
		success: function () {
			alert('Request was successful.');
            if (deleteSelectedItem === selectedItem) {
				selectedItem = null;
				selectedIndex = -1;
			}
            $(`#${deleteSelectedItem.id}`).hide(1);
		},
		error: function (err) {
			alert('An error occurred: ' + err.responseText);
			console.log(err.responseText);
		},
	});
	}
}

var getOptions = function(endpoint, DOM) {

	$.get(baseUrl + "AppTypes/" + endpoint, function(data, status)
	{
        if (status == "success") {
            console.log(data);
            filloptionsToSelectBox(DOM, data);
        }
        else {
            alert(data.responseText);
		}
	});
}

var filloptionsToSelectBox = function(DOM, dataset) {
    
	let dataRow = "";

	dataset.forEach((option, idx) => {
        dataRow += 
		`
		<option value=${option.id}>${option.name}</option>
		`;
    });

    DOM.append(dataRow);
}

$("#btn-refresh").click(getAllItems);

$("#form_update_close").click(() => {
    $("#form_update").hide(1);
})

$("#btn-create").click(() => {

	$("#form_create").show(1);
});

$("#form_create_close").click(() => {
    $("#form_create").hide(1);
})

var Init = function() {
	$("#loading").hide();
    $("#table_items").hide();
    $("#form_update").hide();
    $("#form_create").hide();

    getAllItems();
    getOptions("GetCities", $("select[name='City']"));
    getOptions("GetStates", $("select[name='State']"));
    getOptions("GetCountries", $("select[name='Country']"));
}();

// create publisher use ajax
var frm = $('#form_create');
frm.submit(function (e) {
	// don't submit form yet
	e.preventDefault();

    var object = {};
	// get value from form stackoverflow
	(new FormData(e.target)).forEach(function(value, key){
		// check can parse from string to int or not
		if(key != "Phone" && key != "ZipCode" && !isNaN(value)){
			value = parseFloat(value);
		}
		object[key] = value;
	});

	var json = JSON.stringify(object);

    console.log("Submit(post): " + json);

	$.ajax({
		type: 'post',
        headers: {
			"Content-Type": "application/json"
		},
		url: baseUrl + "Authors",
		data: json,
		// onsuccess
		success: function (item) {
			alert('Create publisher was successful, Id=' + item.id);
				console.log(item);
		},
		// onerror
		error: function (err) {
			alert('An error occurred: ' + err.responseText);
			console.log(err.responseText);
		},
	});
});


// update publisher use ajax
var updateFrm = $('#form_update');
updateFrm.submit(function (e) {
	// don't submit form yet
	e.preventDefault();

	var object = {};
	// get value from form stackoverflow
	(new FormData(e.target)).forEach(function (value, key) {
		// check can parse from string to int or not
		if (key != "Phone" && key != "ZipCode" && !isNaN(value)) {
			value = parseFloat(value);
		}
		object[key] = value;
	});

	var json = JSON.stringify(object);

	console.log("Submit(put): " + json);

	$.ajax({
		type: 'put',
		headers: {
			"Content-Type": "application/json"
		},
		url: baseUrl + "Authors",
		data: json,
		// onsuccess
		success: function (item) {
			alert('Update publisher was successful, Id=' + item.id);
			console.log(item);

			let newRow =
				`
				<tr id="${item.id}">
					<td>${item.id}</td>
					<td>${item.fullName}</td>
					<td>${item.phone}</td>
					<td>${item.email}</td>
					<td>${item.address}</td>
					<td>${item.city.name}</td>
					<td>${item.state.name}</td>
					<td>${item.zipCode}</td>
					<td>
						<button name="btn-update" class="btn btn-success m-1" value="${selectedIndex}">Edit</button>
						<button name="btn-delete" class="btn btn-danger m-1" value="${selectedIndex}">Remove</button>
					</td>
				<tr>
				`;
			$(`#${item.id}`).replaceWith(newRow); 
			itemList[selectedIndex] = item;
			addFillDataEvent();
		},
		// onerror
		error: function (err) {
			alert('An error occurred: ' + err.responseText);
			console.log(err.responseText);
		},
	});
});

</script>

}

WebClient/Views/Books/_BookCreate.cshtml
@{
	
}

WebClient/Views/Home/Detail.cshtml
@using WebClient.Extentions
@using static WebApi.Controllers.IdentityController

@{
    ViewData["Title"] = "Detail";
    TokenResponse auth = SessionManager.Authenticate(Context); 
}
<h1>@ViewData["Title"]</h1>

@if(auth == null) 
{
    <div class="text-center">
        <h1 class="display-6">Welcome to PhucHT's BookStore</h1>
        <p>If you do not account, please <a asp-controller="Users" asp-action="Register"> register here</a>.</p>
        <p>If you have account,<a asp-controller="Login" asp-action="Index"> login here</a>.</p>
    </div>
}

@if(auth != null)
{
    <hr />
    <div class="text-right">
        <a class="btn btn-danger" asp-controller="Logout" asp-action="Index">Logout</a>
    </div>
    <hr />
    if(auth.User.Role.Description == "Admin")
    {
    <h4>Hello Admin, @auth.User.FullName!</h4>
    <hr />
    <a asp-controller="Users" asp-action="Index" class="btn btn-primary">Users Panel</a>
    <a asp-controller="Publishers" asp-action="Index" class="btn btn-primary">Publishers Panel</a>
    <a asp-controller="Authors" asp-action="Index" class="btn btn-primary">Authors Panel</a>
    <a asp-controller="Books" asp-action="Index" class="btn btn-primary">Books Panel</a>
    }
    if(auth.User.Role.Description == "Customer")
    {
        <h4>Hello Customer, @auth.User.FullName!</h4>
    }
}

<hr />

<div class="container">
    @foreach (var item in ViewBag.Book)
    {
        <span> @item.Title </span>
        <img src="https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGJvb2t8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60"
             class="card-img-top" height="220">
        <a href="@item.UrlDownload">Link Download</a>
    }
</div>

WebClient/Views/Home/Index.cshtml
@using WebClient.Extentions
@using static WebApi.Controllers.IdentityController
@{
    ViewData["Title"] = "Home Page";
    TokenResponse auth = SessionManager.Authenticate(Context); 
}


@if(auth == null) 
{
    <div class="text-center">
        <h1 class="display-6">Welcome to PhucHT's BookStore</h1>
        <p>If you do not account, please <a asp-controller="Users" asp-action="Register"> register here</a>.</p>
        <p>If you have account,<a asp-controller="Login" asp-action="Index"> login here</a>.</p>
    </div>
}

@if(auth != null)
{
    <hr />
    <div class="text-right">
        <a class="btn btn-danger" asp-controller="Logout" asp-action="Index">Logout</a>
    </div>
    <hr />
    if(auth.User.Role.Description == "Admin")
    {
    <h4>Hello Admin, @auth.User.FullName!</h4>
    <hr />
    <a asp-controller="Users" asp-action="Index" class="btn btn-primary">Users Panel</a>
    <a asp-controller="Publishers" asp-action="Index" class="btn btn-primary">Publishers Panel</a>
    <a asp-controller="Authors" asp-action="Index" class="btn btn-primary">Authors Panel</a>
    <a asp-controller="Books" asp-action="Index" class="btn btn-primary">Books Panel</a>
    }
    if(auth.User.Role.Description == "Customer")
    {
        <h4>Hello Customer, @auth.User.FullName!</h4>
    }
}

<hr />

<div class="container">
    <br />
    <div class="d-flex justify-content-between">
	<h3>All Books</h3>
    <form method="get" id="form_search" class="d-flex align-items-center" style="gap:10px;">
        <input type="text" name="search" class="form-control" placeholder="Enter a name or price"/>
        <button type="submit" class="btn btn-primary">
            Search
        </button>
    </form>
    </div>
	<hr />
	<div class="d-flex justify-content-center">
		<div id="loading" class="spinner-border text-secondary" role="status">
			<span class="sr-only">Loading...</span>
		</div>
	</div>
	<div class="row" id="flexbox_items"></div>
</div>


@section Scripts 
{
<script>

var baseUrl = "https://localhost:44310/api/";
var itemList = [];
var selectedItem = null;
var selectedIndex = -1;

var getAllItems = function() {

	$("#flexbox_items").show();
    $("#loading").show();

	$.get(baseUrl + "Books", function(data, status)
	{
        if (status == "success") {
			$("#loading").hide(0.5);
            itemList = data;
            console.log(itemList);
            renderItems(itemList);
        }
        else {
            alert(data);
		}
	});
}

var renderItems = function(dataset) {
            
    let dataRow = "";
	
	dataset.forEach((item, idx) => {
        dataRow += BookRenderer(item);
    });

    // console.log(dataRow);

    $("#flexbox_items").html(dataRow);
    addFillDataEvent();

}

var addFillDataEvent = () => {
	
}

$("#form_search input").on('input',function(e) {

    e.preventDefault();

    let search = $("input[name='search']").val();
    console.log(search);
    $.get(baseUrl + "Books/Search?search=" + search, function(data, status)
	{
        $("#flexbox_items").show();
        $("#loading").show();

        if (status == "success") {
			$("#loading").hide(0.5);
            itemList = data;
            console.log(itemList);
            renderItems(itemList);
        }
        else {
            alert(data);
		}
	});

});

var Init = function() {
	$("#loading").hide();
    $("#flexbox_items").hide();
    //$("#form_update").hide();
    //$("#form_create").hide();

    getAllItems();
    //getOptions("GetCities", $("select[name='City']"));
    //getOptions("GetStates", $("select[name='State']"));
    //getOptions("GetCountries", $("select[name='Country']"));
}

Init();

;

</script>

}

WebClient/Views/Login/Index.cshtml
@using WebApi.Models.Identities
@{
	ViewData["Title"] = "Login";
}

@model LoginModel

@if(ViewBag.ApiMessage != null) 
{
	<div class="alert alert-warning">
		<strong>API Message: </strong>
		<span>@ViewBag.ApiMessage</span>
	</div>
}

<div class="p-5 rounded"
	 style="
			height: 80vh;
			background-image: url(https://images.unsplash.com/photo-1549675584-91f19337af3d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1172&q=80);
			background-repeat: no-repeat;
			background-size: cover;
			background-position: 50%;
">

	<div class="d-flex justify-content-end">
		
		<div class="p-5 rounded text-dark" style="background-color: rgba(255, 255, 255)">
			<h2 class="text-center">Welcome to BookStore</h2>
			<hr />
			<form method="post">

				<div class="form-group">
					<label asp-for="Email"></label>
					<input asp-for="Email" class="form-control" />
					<span class="d-block text-danger bg-white font-weight-bold px-2 my-2 rounded" asp-validation-for="Email"></span>
				</div>
				<div class="form-group">
					<label asp-for="Password"></label>
					<input asp-for="Password" type="password" class="form-control" />
					<span class="d-block text-danger bg-white font-weight-bold px-2 my-2 rounded" asp-validation-for="Password"></span>
				</div>
				<div class="form-group text-right">
					<button type="submit" class="btn btn-primary px-4">Login</button>
				</div>

			</form>
			<hr />
			<span>You do not have account?</span>
			<a class="text-black" asp-controller="Users" asp-action="Register">Register here</a>

		</div>


	</div>

</div>

WebClient/Views/Shared/_Layout.cshtml
@using WebClient.Extentions
@using static WebApi.Controllers.IdentityController
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebClient</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @{
        TokenResponse auth = SessionManager.Authenticate(Context);
        if(auth != null)
        {
            <script>
            $.ajaxSetup({
		        headers:{
                    'Authorization': "Bearer " + "@auth.AccessToken"
		        }
		    });
            </script>
        }
    }

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>